### ISSUE TITLE
Syntax errors in torrent_api

### ISSUE THREAD

**Issue by binury** [hjhart/the_rotten_pirate#1]
$ rake execute
rake aborted!
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:55: odd number list for Hash
        [{ page: 1, pages: 1, crc: "9b235c98e2...
                ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:55: syntax error, unexpected ':', expecting '}'
        [{ page: 1, pages: 1, crc: "9b235c98e2...
                ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:55: syntax error, unexpected ',', expecting kEND
...5c98e242f2617ae61dc416ec0de7", id: @id }]
                              ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: odd number list for Hash
          { page: i, pages: params[:pages], crc...
                 ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: syntax error, unexpected ':', expecting '}'
          { page: i, pages: params[:pages], crc...
                 ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: syntax error, unexpected ':', expecting '='
          { page: i, pages: params[:pages], crc: params[:...
                           ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: syntax error, unexpected ':', expecting '='
...i, pages: params[:pages], crc: params[:crc], id: params[:id]...
                              ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: syntax error, unexpected ':', expecting '='
...pages], crc: params[:crc], id: params[:id] }
                              ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:60: syntax error, unexpected '}', expecting kEND
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:70: odd number list for Hash
      { page: page, pages: pages, crc: crc, id: id }
             ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:70: syntax error, unexpected ':', expecting '}'
      { page: page, pages: pages, crc: crc, id: id }
             ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:70: syntax error, unexpected ':', expecting '='
      { page: page, pages: pages, crc: crc, id: id }
                          ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:70: syntax error, unexpected ':', expecting '='
      { page: page, pages: pages, crc: crc, id: id }
                                      ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:70: syntax error, unexpected ':', expecting '='
      { page: page, pages: pages, crc: crc, id: id }
                                               ^
/Library/Ruby/Gems/1.8/gems/torrent_api-0.2.2/lib/pirate_bay/details.rb:112: syntax error, unexpected $end, expecting kEND

Tasks: TOP => execute

**Comment by hjhart** [comment]
This is most definitely because I wrote a hash in the ruby-1.9.2 format. It's choking in 1.8.7.

Try upgrading to ruby 1.9.2 to see if it fixes the problem. Then, tonight, I can go back and change the torrent_api gem to be 1.8.7 compatible too.

**Comment by hjhart** [comment]
I updated the code to support 1.8.7. This should be fixed now.
