### ISSUE TITLE
Problem with movies with slashes in the name

### ISSUE THREAD

**Issue by kjvarga** [hjhart/the_rotten_pirate#5]
I'm seeing this issue with the latest head e647cf906dd8797a

<pre>
I, [2012-01-25T00:28:47.814939 #49126]  INFO -- : Searching...
I, [2012-01-25T00:28:48.134137 #49126]  INFO -- : Filtering...
I, [2012-01-25T00:28:48.210375 #49126]  INFO -- : ********************************************************************************
I, [2012-01-25T00:28:48.210464 #49126]  INFO -- : Attempting to download the following titles: 
I, [2012-01-25T00:28:48.210636 #49126]  INFO -- : ["50/50"]
I, [2012-01-25T00:28:48.210720 #49126]  INFO -- : ********************************************************************************
I, [2012-01-25T00:28:48.210864 #49126]  INFO -- : ********************************************************************************
I, [2012-01-25T00:28:48.210984 #49126]  INFO -- : Searching for 50/50
I, [2012-01-25T00:28:48.211107 #49126]  INFO -- : ********************************************************************************
rake aborted!
No such file or directory - tmp/searches/50/50_200_0.html
</pre>

**Comment by hjhart** [comment]
Ah, interesting. Feel free to submit a pull request with some kind of
file system escaping implemented.

Otherwise hopefully I'll get around to it soon.

James

On Jan 25, 2012, at 12:31 AM, Karl Varga
reply@reply.github.com
wrote:

**Comment by rpardini** [comment]
The problem lies not in the_rotten_pirate, but in torrent_api gem.
https://github.com/hjhart/torrent_api/blob/master/lib/pirate_bay/base.rb at line 40 if I'm not mistaken, a 

```
 search_string.tr("/\000", "") 
```

is enough.
But then once that is overcome, there are other troubles with this title ("50/50") since it does not find it on piratebay, and then bombs...

**Comment by rpardini** [comment]
Thanks for the_rotten_pirate!

**Comment by hjhart** [comment]
This no longer crashes with the newest update of the torrent_api gem. If you do a 

```
 git pull origin master
 bundle
 rake execute
```

This should now be working.

**Comment by rpardini** [comment]
Thanks hjhart. It does not bomb anymore. Unfortunately it also does not find anything at TPB with that name...

**Comment by hjhart** [comment]
I think if we change the search string to use a dot (or space) instead
of a slash it would work. It makes the search URL behave poorly.

I'll try and fix that part soon (but at least it doesn't crash anymore).

James

(sent from my mobile device)

http://www.hjhart.com

On Jan 31, 2012, at 6:30 AM, Ricardo Pardini
reply@reply.github.com
wrote:
